version: ~> 1.0
os: linux
dist: xenial
language: shell

env:
  global:
    - BACKEND_BUILD_DIR=$TRAVIS_BUILD_DIR
    - FRONTEND_BUILD_DIR=$TRAVIS_BUILD_DIR/src/main/frontend

jobs:
  include:
    - language: java
      jdk: openjdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        yarn: true
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_install:
        - cd $BACKEND_BUILD_DIR
        - chmod +x gradlew
      install:
        - ./gradlew assemble
      script:
        - ./gradlew ktlintCheck
        - ./gradlew check
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: node_js
      node_js: lts/*
      cache:
        yarn: true
      before_install:
        - cd $FRONTEND_BUILD_DIR
      install:
        - yarn
      script:
        - yarn lint
        - yarn build
        - yarn test:ci
      after_success:
        - yarn codecov:upload
