os: linux
dist: xenial
language: minimal
env:
  global:
    - BACKEND_BUILD_DIR=$TRAVIS_BUILD_DIR
    - FRONTEND_BUILD_DIR=$TRAVIS_BUILD_DIR/src/main/frontend
jobs:
  - language: java
    jdk: openjdk8
    before_install:
      - cd $BACKEND_BUILD_DIR
    install:
      - ./gradlew assemble
    script:
      - ./gradlew check
      - ./gradlew test
      - ./gradlew build
  - language: node_js
    node_js: node
    before_install:
      - cd $FRONTEND_BUILD_DIR
    install:
      - yarn
    script:
      - yarn lint
      - yarn test
      - yarn build
