version: ~> 1.0
os: linux
dist: xenial
language: shell

env:
  global:
    - BACKEND_BUILD_DIR=$TRAVIS_BUILD_DIR
    - FRONTEND_BUILD_DIR=$TRAVIS_BUILD_DIR/src/main/frontend
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"

jobs:
  include:
    - language: java
      jdk: openjdk8
      before_cache:
        - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
        - bash .clean_gradle_cache.sh
      cache:
        yarn: true
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_install:
        - cd $BACKEND_BUILD_DIR
        - chmod +x gradlew
      install:
        - ./gradlew assemble
      script:
        - ./gradlew ktlintCheck
        - ./gradlew check
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: node_js
      node_js: lts/*
      cache:
        yarn: true
      before_install:
        - cd $FRONTEND_BUILD_DIR
      install:
        - yarn
      script:
        - yarn lint
        - yarn build
        - yarn test:ci
      after_success:
        - yarn codecov:upload
