openapi: 3.0.2

info:
  title: Protelis on the Web API
  description: REST API to communicate with Protelis backend
  version: "1.0"
  contact:
    name: "Niccolò Maltoni"
    url: "https://github.com/NiccoMlt/Protelis-Web"
    email: "niccolo.maltoni@studio.unibo.it"
  license:
    name: "GNU General Public License v3"
    url: "https://github.com/NiccoMlt/Protelis-Web/blob/master/LICENSE"

servers:
  - url: "http://localhost:8080/api"
    description: Local executed server

paths:
  /message:
    get:
      tags:
        - demo
      summary: Get message.
      description: Get example Vert.x message.
      operationId: getMessage
      responses:
        200:
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: Hello React from Vert.x!
        default:
          description: Unsuccessful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
