import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val org_jetbrains_kotlin: String = "1.3.50"

  const val org_jetbrains_dokka: String = "0.10.0"

  const val org_junit_jupiter: String = "5.5.2"

  const val io_vertx: String = "3.8.4"

  const val com_github_johnrengelman_shadow_gradle_plugin: String = "5.2.0"

  const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String = "9.0.0" // available: "9.1.0"

  const val com_github_node_gradle_node_gradle_plugin: String = "2.2.0"

  const val de_fayard_refreshversions_gradle_plugin: String = "0.7.0" // available: "0.8.1"

  const val org_jetbrains_kotlin_kapt_gradle_plugin: String = "1.3.50"

  const val org_jetbrains_kotlin_jvm_gradle_plugin: String = "1.3.50"

  const val io_vertx_vertx_plugin_gradle_plugin: String = "1.0.1"

  const val logback_classic: String = "1.2.3"

  const val kotlin_logging: String = "1.7.6"

  const val slf4j_api: String = "1.7.28" // available: "1.7.29"

  const val ktlint: String = "0.34.2" // available: "0.35.0"

  /**
   * Current version: "5.6.3"
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "5.6.4"
}
