import org.gradle.api.JavaVersion
import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {

  const val io_vertx: String = "3.8.5"

  val java_version: JavaVersion = JavaVersion.VERSION_11
  val jdk_version: String = this.java_version.toString()
}
