version: 1

update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: "javascript"
    directory: "/src/main/frontend"
    update_schedule: "live"
    commit_message:
      prefix: "chore"
      include_scope: true
